### ISSUE TITLE
Stats not created when player join the lobby for the first time

### ISSUE THREAD

**Issue by porudev** [tomkeuper/BWProxy2023#1]
![image](https://user-images.githubusercontent.com/81072838/234235532-23225fbe-90cf-41d0-8639-4bdbf50b076a.png)
![image](https://user-images.githubusercontent.com/81072838/234235548-9be3b698-bce9-4980-bceb-6894538a3a59.png)

2 Image 1 from forcefully joining the Game Server with /server
second is from the BedwarProxy lobby with level and required experience not returning any value

**Comment by porudev** [comment]
I fixed it my self

**Comment by porudev** [comment]
we need to find an actual fix

**Comment by tomkeuper** [comment]
This is fixed in 753f3e8b7a46d6d2a141604a1e2750095e8dc0a1
