### ISSUE TITLE
levels.yml

### ISSUE THREAD

**Issue by ritana5** [tomkeuper/BWProxy2023#27]
**Is your feature request related to a problem? Please describe.**
The current `level-settings` in `config.yml` is not as useful as the main plugin one as you cant customize per level.

**Describe the solution you'd like**
I would like the `levels.yml` from BedWars2023 to also be in BWProxy2023 instead of a small section in the `config.yml`.

**Describe alternatives you've considered**
Haven't thought of any other way.

**Comment by tomkeuper** [comment]
The level format is retrieved from the database. And for new players there is an default format since they dont have an entry in the database

**Comment by ritana5** [comment]
Oh I see thanks!
